PACKAGE_NAME="hp-wmi-fan-ctrl"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="hp_wmi_fan_ctrl"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
